object_name: Alala A2
Designer: [Martins Alice](http://a2spaceater.tumblr.com/), [De Pin Alizée](http://www.alizeedepin.com/), [Landes Jérémy](http://jjllnn.fr)
Builder: [Martins Alice](http://a2spaceater.tumblr.com/), [De Pin Alizée](http://www.alizeedepin.com/), [Landes Jérémy](http://jjllnn.fr), [Rousseau Manon](http://manonrousseau.tumblr.com/)
tags: wood
creation_date: 01-2015
contributors: none
derived_from: none
realisation_place: [La Nouvelle Fabrique](http://www.nouvellefabrique.fr/), Paris
required_hardware: CNC
Materials: 10 mm thick medium density fiberboard (MDF)
Advantage: No screws, can be dismantled.
Licence: [Free Art Licence](http://artlibre.org/licence/lal/en/)
client: none

content: +++
A CNC cut paper rack made to store A2 portfolios. No screws nor nails nor glue needed, it's just a puzzle.
Can be scaled to make a rack holding bigger portfolios, just beware of the thickness of the material and the matching size of the notches.
+++